name = "DST Pack"
author = "studkid"
version = "ALPHA-0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "256975800a34fd40168d02d45ff9141966a057982a5165be78872378cab6c879"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"
