name = "DST Pack"
author = "studkid"
version = "ALPHA-0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79abf599fdf93ba5ae369fd45a884b20a6745312bf0ed2b860b20995536ba432"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"
