name = "DST Pack"
author = "studkid"
version = "ALPHA-0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83c76800fbe98fa19c49242cd4caeafdd7af57d18f1ce8560449dc30b6ee3bd6"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"
