name = "DST Pack"
author = "studkid"
version = "ALPHA-0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b78c26594fa4b9a4ee279027df8d5df4b750959854f8996a3ddfe5eb0a17d38"

[versions]
forge = "47.2.1"
minecraft = "1.20.1"
